name: PR PRSK labeling

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  add-character-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add PRSK label
        uses: Narumikr/link-sekai-actions/prsk-pr-labeling@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}